version: 0.0
os: linux
files:
  - source: ./build/libs/financial-0.0.1-SNAPSHOT.war
    destination: /tmp/CodeDeployExample/
hooks:
  BeforeInstall:
    - location: ./scripts/before-install.sh
      timeout: 30
  AfterInstall:
    - location: ./scripts/after-install.sh
      timeout: 30
  ApplicationStop:
    - location: ./scripts/application-stop.sh
      timeout: 30
  ApplicationStart:
    - location: ./scripts/application-start.sh
      timeout: 30
  ValidateService:
    - location: ./scripts/validate-service.sh
      timeout: 30